package com.cmgy.model;

import java.math.BigDecimal;
import java.util.Date;

public class SpPostingFlow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.pid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.t_id
     *
     * @mbggenerated
     */
    private String tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.inter_msg_id
     *
     * @mbggenerated
     */
    private String interMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.accounting_id
     *
     * @mbggenerated
     */
    private String accountingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.batch_id
     *
     * @mbggenerated
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.accounting_type
     *
     * @mbggenerated
     */
    private String accountingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.accounting_status
     *
     * @mbggenerated
     */
    private String accountingStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_account
     *
     * @mbggenerated
     */
    private String postingAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.merch_id
     *
     * @mbggenerated
     */
    private String merchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.crdr_flag
     *
     * @mbggenerated
     */
    private String crdrFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_account_type
     *
     * @mbggenerated
     */
    private String postingAccountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_type
     *
     * @mbggenerated
     */
    private String postingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_curreny
     *
     * @mbggenerated
     */
    private String postingCurreny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_amount
     *
     * @mbggenerated
     */
    private BigDecimal postingAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.balance
     *
     * @mbggenerated
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.rate
     *
     * @mbggenerated
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_date
     *
     * @mbggenerated
     */
    private Date postingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.posting_time
     *
     * @mbggenerated
     */
    private Date postingTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.mid
     *
     * @mbggenerated
     */
    private String mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.voucher
     *
     * @mbggenerated
     */
    private String voucher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.mop
     *
     * @mbggenerated
     */
    private String mop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.core_account_id
     *
     * @mbggenerated
     */
    private String coreAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.core_account_date
     *
     * @mbggenerated
     */
    private Date coreAccountDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.core_settlement_date
     *
     * @mbggenerated
     */
    private Date coreSettlementDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.core_posting_office_id
     *
     * @mbggenerated
     */
    private String corePostingOfficeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.cort_account
     *
     * @mbggenerated
     */
    private String cortAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.input_opt_id
     *
     * @mbggenerated
     */
    private String inputOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.recon_id
     *
     * @mbggenerated
     */
    private String reconId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.chk_opt_id
     *
     * @mbggenerated
     */
    private String chkOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.verify_opt_id
     *
     * @mbggenerated
     */
    private String verifyOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.auth_opt_id
     *
     * @mbggenerated
     */
    private String authOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.appr_opt_id
     *
     * @mbggenerated
     */
    private String apprOptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.create_datetime
     *
     * @mbggenerated
     */
    private Date createDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.modify_datetime
     *
     * @mbggenerated
     */
    private Date modifyDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.msgderid
     *
     * @mbggenerated
     */
    private String msgderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.msgxml
     *
     * @mbggenerated
     */
    private String msgxml;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.orgnl_msg_id
     *
     * @mbggenerated
     */
    private String orgnlMsgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sp_posting_flow.orgnl_t_id
     *
     * @mbggenerated
     */
    private String orgnlTId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.pid
     *
     * @return the value of sp_posting_flow.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.pid
     *
     * @param pid the value for sp_posting_flow.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.id
     *
     * @return the value of sp_posting_flow.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.id
     *
     * @param id the value for sp_posting_flow.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.t_id
     *
     * @return the value of sp_posting_flow.t_id
     *
     * @mbggenerated
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.t_id
     *
     * @param tId the value for sp_posting_flow.t_id
     *
     * @mbggenerated
     */
    public void settId(String tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.inter_msg_id
     *
     * @return the value of sp_posting_flow.inter_msg_id
     *
     * @mbggenerated
     */
    public String getInterMsgId() {
        return interMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.inter_msg_id
     *
     * @param interMsgId the value for sp_posting_flow.inter_msg_id
     *
     * @mbggenerated
     */
    public void setInterMsgId(String interMsgId) {
        this.interMsgId = interMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.accounting_id
     *
     * @return the value of sp_posting_flow.accounting_id
     *
     * @mbggenerated
     */
    public String getAccountingId() {
        return accountingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.accounting_id
     *
     * @param accountingId the value for sp_posting_flow.accounting_id
     *
     * @mbggenerated
     */
    public void setAccountingId(String accountingId) {
        this.accountingId = accountingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.batch_id
     *
     * @return the value of sp_posting_flow.batch_id
     *
     * @mbggenerated
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.batch_id
     *
     * @param batchId the value for sp_posting_flow.batch_id
     *
     * @mbggenerated
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.accounting_type
     *
     * @return the value of sp_posting_flow.accounting_type
     *
     * @mbggenerated
     */
    public String getAccountingType() {
        return accountingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.accounting_type
     *
     * @param accountingType the value for sp_posting_flow.accounting_type
     *
     * @mbggenerated
     */
    public void setAccountingType(String accountingType) {
        this.accountingType = accountingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.accounting_status
     *
     * @return the value of sp_posting_flow.accounting_status
     *
     * @mbggenerated
     */
    public String getAccountingStatus() {
        return accountingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.accounting_status
     *
     * @param accountingStatus the value for sp_posting_flow.accounting_status
     *
     * @mbggenerated
     */
    public void setAccountingStatus(String accountingStatus) {
        this.accountingStatus = accountingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_account
     *
     * @return the value of sp_posting_flow.posting_account
     *
     * @mbggenerated
     */
    public String getPostingAccount() {
        return postingAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_account
     *
     * @param postingAccount the value for sp_posting_flow.posting_account
     *
     * @mbggenerated
     */
    public void setPostingAccount(String postingAccount) {
        this.postingAccount = postingAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.merch_id
     *
     * @return the value of sp_posting_flow.merch_id
     *
     * @mbggenerated
     */
    public String getMerchId() {
        return merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.merch_id
     *
     * @param merchId the value for sp_posting_flow.merch_id
     *
     * @mbggenerated
     */
    public void setMerchId(String merchId) {
        this.merchId = merchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.crdr_flag
     *
     * @return the value of sp_posting_flow.crdr_flag
     *
     * @mbggenerated
     */
    public String getCrdrFlag() {
        return crdrFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.crdr_flag
     *
     * @param crdrFlag the value for sp_posting_flow.crdr_flag
     *
     * @mbggenerated
     */
    public void setCrdrFlag(String crdrFlag) {
        this.crdrFlag = crdrFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_account_type
     *
     * @return the value of sp_posting_flow.posting_account_type
     *
     * @mbggenerated
     */
    public String getPostingAccountType() {
        return postingAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_account_type
     *
     * @param postingAccountType the value for sp_posting_flow.posting_account_type
     *
     * @mbggenerated
     */
    public void setPostingAccountType(String postingAccountType) {
        this.postingAccountType = postingAccountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_type
     *
     * @return the value of sp_posting_flow.posting_type
     *
     * @mbggenerated
     */
    public String getPostingType() {
        return postingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_type
     *
     * @param postingType the value for sp_posting_flow.posting_type
     *
     * @mbggenerated
     */
    public void setPostingType(String postingType) {
        this.postingType = postingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_curreny
     *
     * @return the value of sp_posting_flow.posting_curreny
     *
     * @mbggenerated
     */
    public String getPostingCurreny() {
        return postingCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_curreny
     *
     * @param postingCurreny the value for sp_posting_flow.posting_curreny
     *
     * @mbggenerated
     */
    public void setPostingCurreny(String postingCurreny) {
        this.postingCurreny = postingCurreny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_amount
     *
     * @return the value of sp_posting_flow.posting_amount
     *
     * @mbggenerated
     */
    public BigDecimal getPostingAmount() {
        return postingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_amount
     *
     * @param postingAmount the value for sp_posting_flow.posting_amount
     *
     * @mbggenerated
     */
    public void setPostingAmount(BigDecimal postingAmount) {
        this.postingAmount = postingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.balance
     *
     * @return the value of sp_posting_flow.balance
     *
     * @mbggenerated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.balance
     *
     * @param balance the value for sp_posting_flow.balance
     *
     * @mbggenerated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.rate
     *
     * @return the value of sp_posting_flow.rate
     *
     * @mbggenerated
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.rate
     *
     * @param rate the value for sp_posting_flow.rate
     *
     * @mbggenerated
     */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_date
     *
     * @return the value of sp_posting_flow.posting_date
     *
     * @mbggenerated
     */
    public Date getPostingDate() {
        return postingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_date
     *
     * @param postingDate the value for sp_posting_flow.posting_date
     *
     * @mbggenerated
     */
    public void setPostingDate(Date postingDate) {
        this.postingDate = postingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.posting_time
     *
     * @return the value of sp_posting_flow.posting_time
     *
     * @mbggenerated
     */
    public Date getPostingTime() {
        return postingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.posting_time
     *
     * @param postingTime the value for sp_posting_flow.posting_time
     *
     * @mbggenerated
     */
    public void setPostingTime(Date postingTime) {
        this.postingTime = postingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.mid
     *
     * @return the value of sp_posting_flow.mid
     *
     * @mbggenerated
     */
    public String getMid() {
        return mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.mid
     *
     * @param mid the value for sp_posting_flow.mid
     *
     * @mbggenerated
     */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.voucher
     *
     * @return the value of sp_posting_flow.voucher
     *
     * @mbggenerated
     */
    public String getVoucher() {
        return voucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.voucher
     *
     * @param voucher the value for sp_posting_flow.voucher
     *
     * @mbggenerated
     */
    public void setVoucher(String voucher) {
        this.voucher = voucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.mop
     *
     * @return the value of sp_posting_flow.mop
     *
     * @mbggenerated
     */
    public String getMop() {
        return mop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.mop
     *
     * @param mop the value for sp_posting_flow.mop
     *
     * @mbggenerated
     */
    public void setMop(String mop) {
        this.mop = mop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.core_account_id
     *
     * @return the value of sp_posting_flow.core_account_id
     *
     * @mbggenerated
     */
    public String getCoreAccountId() {
        return coreAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.core_account_id
     *
     * @param coreAccountId the value for sp_posting_flow.core_account_id
     *
     * @mbggenerated
     */
    public void setCoreAccountId(String coreAccountId) {
        this.coreAccountId = coreAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.core_account_date
     *
     * @return the value of sp_posting_flow.core_account_date
     *
     * @mbggenerated
     */
    public Date getCoreAccountDate() {
        return coreAccountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.core_account_date
     *
     * @param coreAccountDate the value for sp_posting_flow.core_account_date
     *
     * @mbggenerated
     */
    public void setCoreAccountDate(Date coreAccountDate) {
        this.coreAccountDate = coreAccountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.core_settlement_date
     *
     * @return the value of sp_posting_flow.core_settlement_date
     *
     * @mbggenerated
     */
    public Date getCoreSettlementDate() {
        return coreSettlementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.core_settlement_date
     *
     * @param coreSettlementDate the value for sp_posting_flow.core_settlement_date
     *
     * @mbggenerated
     */
    public void setCoreSettlementDate(Date coreSettlementDate) {
        this.coreSettlementDate = coreSettlementDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.core_posting_office_id
     *
     * @return the value of sp_posting_flow.core_posting_office_id
     *
     * @mbggenerated
     */
    public String getCorePostingOfficeId() {
        return corePostingOfficeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.core_posting_office_id
     *
     * @param corePostingOfficeId the value for sp_posting_flow.core_posting_office_id
     *
     * @mbggenerated
     */
    public void setCorePostingOfficeId(String corePostingOfficeId) {
        this.corePostingOfficeId = corePostingOfficeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.cort_account
     *
     * @return the value of sp_posting_flow.cort_account
     *
     * @mbggenerated
     */
    public String getCortAccount() {
        return cortAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.cort_account
     *
     * @param cortAccount the value for sp_posting_flow.cort_account
     *
     * @mbggenerated
     */
    public void setCortAccount(String cortAccount) {
        this.cortAccount = cortAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.input_opt_id
     *
     * @return the value of sp_posting_flow.input_opt_id
     *
     * @mbggenerated
     */
    public String getInputOptId() {
        return inputOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.input_opt_id
     *
     * @param inputOptId the value for sp_posting_flow.input_opt_id
     *
     * @mbggenerated
     */
    public void setInputOptId(String inputOptId) {
        this.inputOptId = inputOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.recon_id
     *
     * @return the value of sp_posting_flow.recon_id
     *
     * @mbggenerated
     */
    public String getReconId() {
        return reconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.recon_id
     *
     * @param reconId the value for sp_posting_flow.recon_id
     *
     * @mbggenerated
     */
    public void setReconId(String reconId) {
        this.reconId = reconId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.chk_opt_id
     *
     * @return the value of sp_posting_flow.chk_opt_id
     *
     * @mbggenerated
     */
    public String getChkOptId() {
        return chkOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.chk_opt_id
     *
     * @param chkOptId the value for sp_posting_flow.chk_opt_id
     *
     * @mbggenerated
     */
    public void setChkOptId(String chkOptId) {
        this.chkOptId = chkOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.verify_opt_id
     *
     * @return the value of sp_posting_flow.verify_opt_id
     *
     * @mbggenerated
     */
    public String getVerifyOptId() {
        return verifyOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.verify_opt_id
     *
     * @param verifyOptId the value for sp_posting_flow.verify_opt_id
     *
     * @mbggenerated
     */
    public void setVerifyOptId(String verifyOptId) {
        this.verifyOptId = verifyOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.auth_opt_id
     *
     * @return the value of sp_posting_flow.auth_opt_id
     *
     * @mbggenerated
     */
    public String getAuthOptId() {
        return authOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.auth_opt_id
     *
     * @param authOptId the value for sp_posting_flow.auth_opt_id
     *
     * @mbggenerated
     */
    public void setAuthOptId(String authOptId) {
        this.authOptId = authOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.appr_opt_id
     *
     * @return the value of sp_posting_flow.appr_opt_id
     *
     * @mbggenerated
     */
    public String getApprOptId() {
        return apprOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.appr_opt_id
     *
     * @param apprOptId the value for sp_posting_flow.appr_opt_id
     *
     * @mbggenerated
     */
    public void setApprOptId(String apprOptId) {
        this.apprOptId = apprOptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.create_datetime
     *
     * @return the value of sp_posting_flow.create_datetime
     *
     * @mbggenerated
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.create_datetime
     *
     * @param createDatetime the value for sp_posting_flow.create_datetime
     *
     * @mbggenerated
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.modify_datetime
     *
     * @return the value of sp_posting_flow.modify_datetime
     *
     * @mbggenerated
     */
    public Date getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.modify_datetime
     *
     * @param modifyDatetime the value for sp_posting_flow.modify_datetime
     *
     * @mbggenerated
     */
    public void setModifyDatetime(Date modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.msgderid
     *
     * @return the value of sp_posting_flow.msgderid
     *
     * @mbggenerated
     */
    public String getMsgderid() {
        return msgderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.msgderid
     *
     * @param msgderid the value for sp_posting_flow.msgderid
     *
     * @mbggenerated
     */
    public void setMsgderid(String msgderid) {
        this.msgderid = msgderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.msgxml
     *
     * @return the value of sp_posting_flow.msgxml
     *
     * @mbggenerated
     */
    public String getMsgxml() {
        return msgxml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.msgxml
     *
     * @param msgxml the value for sp_posting_flow.msgxml
     *
     * @mbggenerated
     */
    public void setMsgxml(String msgxml) {
        this.msgxml = msgxml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.orgnl_msg_id
     *
     * @return the value of sp_posting_flow.orgnl_msg_id
     *
     * @mbggenerated
     */
    public String getOrgnlMsgId() {
        return orgnlMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.orgnl_msg_id
     *
     * @param orgnlMsgId the value for sp_posting_flow.orgnl_msg_id
     *
     * @mbggenerated
     */
    public void setOrgnlMsgId(String orgnlMsgId) {
        this.orgnlMsgId = orgnlMsgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sp_posting_flow.orgnl_t_id
     *
     * @return the value of sp_posting_flow.orgnl_t_id
     *
     * @mbggenerated
     */
    public String getOrgnlTId() {
        return orgnlTId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sp_posting_flow.orgnl_t_id
     *
     * @param orgnlTId the value for sp_posting_flow.orgnl_t_id
     *
     * @mbggenerated
     */
    public void setOrgnlTId(String orgnlTId) {
        this.orgnlTId = orgnlTId;
    }
}